<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EcoStore.Datos\EcoStore.Datos.csproj" />
    <ProjectReference Include="..\EcoStore.Entidades\EcoStore.Entidades.csproj" />
  </ItemGroup>

</Project>
